python data_preprocess/manifold.py
python data_preprocess/manifold.py
python data_preprocess/manifold.py
python data_preprocess/manifold.py
python data_preprocess/manifold.py
python data_preprocess/simplify.py
python data_preprocess/simplify.py
python data_preprocess/simplify.py
python data_preprocess/simplify.py
python data_preprocess/simplify.py
cd ~/SubdivNet
python datagen_maps.py
python datagen_maps.py
python datagen_maps.py
python datagen_maps.py
python datagen_maps.py
cd ~/new_new_teeth
bash pretrain.sh