python train.py train \
	--checkpoint "/data/lcs/new_checkpoints/for_lower_2/loss-0.1482-314.pkl" \
	--total_checkpoint "/data/lcs/new_checkpoints/new_data/best_acc.pkl" \
	--dataroot "/data/lcs/finetuned_teeth/single_after_remesh" \
	--paramroot "/data/lcs/finetuned_teeth/transformed_after_param" \
	--batch_size 8 --n_classes 40 \
	--n_epoch 700 \
	--name "new_data_2" \
	--weight_decay 0.05 \
	--mask_ratio 0.5 \
	--channels 10 --patch_size 64 \
	--lr 4e-4 \
	--weight 0.5 \
	--depth 12 \
	--heads 12 \
	--lr_milestones "none" --optim "adamw" \
	--encoder_depth 12 \
	--decoder_depth 6 \
	--decoder_dim 512 \
	--decoder_num_heads 16 \
	--num_warmup_steps "2" \
	--dim 768 \
	--use_pointnet \
	--lower 