optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0001,
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 500,
    initial_epochs : 10
}}

dataset : {
  train : { NAME: FullTeethDataset,
            train: True,
            file: files/second_stage/train.txt,
            after_path: /data3/leics/dataset/type2/pointcloud512_after,
            axis_path: /data3/leics/dataset/type2/single_after_axis,
            npoint: 512
            },
  val : { NAME: FullTeethDataset,
          train: False,
          file: files/second_stage/test.txt,
          after_path: /data3/leics/dataset/type2/pointcloud512_after,
            axis_path: /data3/leics/dataset/type2/single_after_axis,
          npoint: 512},
  test : {  NAME: FullTeethDataset,
            train: False,
            file: files/second_stage/test.txt,
            after_path: /data3/leics/dataset/type2/pointcloud512_after,
            axis_path: /data3/leics/dataset/type2/single_after_axis,
            npoint: 512}}

model : {
  NAME: VoxelUNet,
   local_encoder: {
    zdim: 512,
    num_dense: 512,
    latent_dim: 512, 
    input_dim: 3,
    n_head: 8,
    grid_size: 4,
    depth: 12
  },
}


npoints: 512
total_bs : 32
kl_weight: 0.5
step_per_update : 1
max_epoch : 500
grad_norm_clip : 10