optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.001,
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 1000,
    initial_epochs : 10
}}

dataset : {
  train : { NAME: FullTeethDataset,
            train: True,
            file: files/second_stage/train.txt,
            # after_path: /data3/leics/dataset/type2/single_after_inside512,
            after_path: /data3/leics/dataset/type2/single_after_pointcloud128,
            axis_path: /data3/leics/dataset/type2/single_after_axis,
            npoint: 128
            },
  val : { NAME: FullTeethDataset,
          train: False,
          file: files/second_stage/test.txt,
          # after_path: /data3/leics/dataset/type2/single_after_inside512,
          after_path: /data3/leics/dataset/type2/single_after_pointcloud128,
            axis_path: /data3/leics/dataset/type2/single_after_axis,
          npoint: 128},
  test : {  NAME: FullTeethDataset,
            train: False,
            file: files/second_stage/test.txt,
            # after_path: /data3/leics/dataset/type2/single_after_inside512,
            after_path: /data3/leics/dataset/type2/single_after_pointcloud128,
            axis_path: /data3/leics/dataset/type2/single_after_axis,
            npoint: 128}}

model : {
  NAME: DiffusionVAE,
  vae: {
    zdim: 64,
    resolution: 4,
    npoint: 128,
    local_encoder: {
    zdim: 64,
    num_dense: 512,
    latent_dim: 512, 
    input_dim: 3,
    n_head: 8,
    grid_size: 4,
    depth: 12
    }
  }
}


npoints: 128
total_bs : 64
step_per_update : 1
max_epoch : 1000
grad_norm_clip : 10
before_mesh_path: /data3/leics/dataset/type2/single_before
after_mesh_path: /data3/leics/dataset/type2/single_after