optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0001,
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs : 10
}}

dataset : {
  train : { NAME: AxisDataset,
            train: True,
            file: files/second_stage/train.txt,
            after_path: /data3/leics/dataset/type2/pointcloud512_after,
            after_axis_path: /data3/leics/dataset/type2/single_after_axis,
            before_path: /data3/leics/dataset/type2/pointcloud512_before,
            before_axis_path: /data3/leics/dataset/type2/single_before_axis,
            npoint: 512
            },
  val : { NAME: AxisDataset,
          train: False,
          file: files/second_stage/test.txt,
          after_path: /data3/leics/dataset/type2/pointcloud512_after,
          after_axis_path: /data3/leics/dataset/type2/single_after_axis,
          before_path: /data3/leics/dataset/type2/pointcloud512_before,
          before_axis_path: /data3/leics/dataset/type2/single_before_axis,
          npoint: 512},
  test : {  NAME: AxisTestDataset,
            train: False,
            file: files/second_stage/test.txt,
            before_path: /data3/leics/dataset/type2/pointcloud512_before,
            npoint: 512}}

model : {
  NAME: Predictor,
  latent_dim: 1024, 
  PCN: {
    num_dense: 512, 
    latent_dim: 1024, 
    grid_size: 4
  }
}


npoints: 512
total_bs : 64
step_per_update : 1
max_epoch : 300
grad_norm_clip : 10
before_mesh_path: /data3/leics/dataset/type2/single_before
after_mesh_path: /data3/leics/dataset/type2/single_after