optimizer : {
  type: Adam,
  kwargs: {
  lr : 0.00001,
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 500,
    initial_epochs : 10
}}

dataset : {
  train : { NAME: FullTeethDataset,
            train: True,
            file: files/second_stage/train.txt,
            after_path: /data3/leics/dataset/type2/pointcloud512_after,
            axis_path: /data3/leics/dataset/type2/single_after_axis,
            npoint: 512
            },
  val : { NAME: FullTeethDataset,
          train: False,
          file: files/second_stage/test.txt,
          after_path: /data3/leics/dataset/type2/pointcloud512_after,
            axis_path: /data3/leics/dataset/type2/single_after_axis,
          npoint: 512},
  test : {  NAME: FullTeethDataset,
            train: False,
            file: files/second_stage/test.txt,
            after_path: /data3/leics/dataset/type2/pointcloud512_after,
            axis_path: /data3/leics/dataset/type2/single_after_axis,
            npoint: 512}}

model : {
  NAME: GlobalVAE,
  ddpm_dim: 3,
  shapelatent_latent_dim: 1,
  latent_dim: 1024, 
  sample_points: 16384,
  style_dim: 128,
  dropout: 0.1,
  skip_weight: 0.01,
  pts_sigma_offset: 0.0,
  log_sigma_offset: 6.0,
  depth: 12,
  ada_mlp_init_scale: 0.1,
  cond_on_cat: False,
}


npoints: 512
total_bs : 64
kl_weight: 0.5
step_per_update : 1
max_epoch : 300
grad_norm_clip : 10