optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0001,
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs : 10
}}

dataset : {
  train : { NAME: teethDataset,
            train: True,
            sample_num: 512,
            file: files/first_stage/train.txt},
  val : { NAME: teethDataset,
          train: False,
          sample_num: 512,
          file: files/first_stage/test.txt},
  test : {  NAME: teethDataset,
            train: False,
            sample_num: 512,
            file: files/first_stage/test.txt}}

model : {
  NAME: PCN,
  num_dense: 512, 
  latent_dim: 512, 
  grid_size: 4
}


npoints: 8192
total_bs : 128
step_per_update : 1
max_epoch : 300
grad_norm_clip : 10