optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0005,
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs : 10
}}

dataset : {
  train : { NAME: teethDataset,
            train: True,
            file: files/first_stage/train.txt},
  val : { NAME: teethDataset,
          train: False,
          file: files/first_stage/test.txt},
  test : {  NAME: teethDataset,
            train: False,
            file: files/first_stage/test.txt}}

model : {
  NAME: PointVAE,
  z_dim: 256,
  in_dim: 3,
}


total_bs : 32
step_per_update : 1
max_epoch : 300