optimizer: { type: AdamW, kwargs: { lr: 0.0001, weight_decay: 0.05 } }

scheduler: { type: CosLR, kwargs: { epochs: 500, initial_epochs: 20 } }

dataset : {
  train : { NAME: teethDataset,
            train: True,
            file: files/pretrain/train.txt,
            },
  val : { NAME: teethDataset,
          train: False,
          file: files/pretrain/test.txt,},
  test : {  NAME: teethDataset,
            train: False,
            file: files/pretrain/test.txt,
            }}

npoints: 512
total_bs: 512
step_per_update: 1
max_epoch: 500
