optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0005,
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs : 10
}}

dataset : {
  train : { NAME: teethDataset,
            train: True,
            sample_num: 1024,
            file: files/first_stage/train.txt},
  val : { NAME: teethDataset,
          train: False,
          sample_num: 1024,
          file: files/first_stage/test.txt},
  test : {  NAME: teethDataset,
            train: False,
            sample_num: 1024,
            file: files/first_stage/test.txt}}

model : {
  NAME: GlobalVAE,
  ddpm_dim: 3,
  shapelatent_latent_dim: 1,
  latent_dim: 256, 
  sample_points: 1024,
  style_dim: 128,
  dropout: 0.1,
  skip_weight: 0.01,
  pts_sigma_offset: 0.0,
  log_sigma_offset: 6.0,
  depth: 12,
  ada_mlp_init_scale: 0.1,
  cond_on_cat: False,
}


npoints: 1024
total_bs : 64
kl_weight: 0.5
step_per_update : 1
max_epoch : 300
grad_norm_clip : 10