optimizer: { type: AdamW, kwargs: { lr: 0.0001, weight_decay: 0.05 } }

scheduler: { type: CosLR, kwargs: { epochs: 300, initial_epochs: 5 } }

dataset : {
  train : { NAME: DentalDataset,
            train: True,
            dataroot: */remesh_before,  
            paramroot: */param,
            before_path: */pcd_before512,
            after_path: */pcd_after512,
            npoint: 512,
            file: *,
            },
  val : { NAME: DentalDataset,
            train: True,
            dataroot: */remesh_before,  
            paramroot: */param,
            before_path: */pcd_before512,
            after_path: */pcd_after512,
            npoint: 512,
            file: *,
            },
  test : { NAME: DentalDataset,
            train: True,
            dataroot: */remesh_before,  
            paramroot: */param,
            before_path: */pcd_before512,
            after_path: */pcd_after512,
            npoint: 512,
            file: *,
            }}

model:
  {
    NAME: TADPM,
    dim: 768,
    depth: 12,
    num_heads: 8,
  }

npoints: 512
total_bs: 32
step_per_update: 1
max_epoch: 300
